include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_relative_lib_imports
    - prefer_relative_imports

analyzer:
  exclude:
    - example/**
    - examples/**

formatter:
  page_width: 120
  trailing_commas: preserve

# TODO other rules, especially to prevent default values
