name: taptest
description: Flutter testing framework for user-facing widget and integration tests with snapshot support.
version: 1.0.0
homepage: https://taptest.dev
repository: https://github.com/chris-rutkowski/taptest
issue_tracker: https://github.com/chris-rutkowski/taptest/issues
documentation: https://taptest.dev
topics:
  - testing
  - flutter

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  crypto: ^3.0.0
  device_info_plus: ">=11.0.0 <15.0.0"
  fake_http_client: ^2.0.0
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  material_ui: ^1.0.0
  meta: ^1.16.0
  path: ^1.8.0
  platform: ^3.0.0
  taptest_runtime: ^1.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  go_router: ^18.0.0

flutter:
