import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // TapTest Tutorial - A structured 5-page tutorial for learning TapTest
  tutorialSidebar: [
    {
      type: 'category',
      label: 'TapTest Tutorial',
      items: [
        'tutorial/getting-started',
        'tutorial/starter-project',
        'tutorial/add-taptest',
        'tutorial/widget-vs-integration-tests',
        'tutorial/first-test',
        'tutorial/testing-counter',
        'tutorial/thousand-taps-challenge',
        'tutorial/testing-form',
        'tutorial/pop-screen',
        'tutorial/advanced-techniques',
        'tutorial/configuration',
        'tutorial/best-practices',
      ],
    },
    {
      type: 'category',
      label: 'Actions Reference',
      items: [{ type: 'autogenerated', dirName: 'actions' }],
    },
  ],
}

export default sidebars
