import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'install',
    'first-test',
    'config',
    'snapshots',
    'http-mocks',
    {
      type: 'category',
      label: 'Actions',
      items: [{type: 'autogenerated', dirName: 'actions'}],
    },
  ],
};

export default sidebars;
