name: Flutter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Flutter Tests
    runs-on: macos-15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Flutter version
      id: flutter_version
      run: echo "version=$(cat flutter-version.txt)" >> $GITHUB_OUTPUT

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.flutter_version.outputs.version }}
        cache: true

    - name: Get package dependencies
      run: flutter pub get
      working-directory: ./

    - name: Get example dependencies
      run: flutter pub get
      working-directory: ./example

    - name: Analyze package code
      run: flutter analyze
      working-directory: ./

    - name: Analyze example code
      run: flutter analyze
      working-directory: ./example

    - name: Run package tests
      run: flutter test
      working-directory: ./

    - name: Run example tests
      run: flutter test
      working-directory: ./example

    - name: Check formatting
      run: |
        find . -name "*.dart" ! -path "./example/*" ! -path "./.dart_tool/*" ! -name "*.g.dart" ! -name "*.freezed.dart" | xargs dart format --set-exit-if-changed
      working-directory: ./

    - name: Check example formatting
      run: |
        find . -name "*.dart" ! -path "./.dart_tool/*" ! -name "*.g.dart" ! -name "*.freezed.dart" | xargs dart format --set-exit-if-changed
      working-directory: ./example
