name: Integration Tests iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration_test_ios:
    name: Run Integration Tests on iPhone 16 Pro
    runs-on: macos-15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Flutter version
      id: flutter_version
      run: echo "version=$(cat flutter-version.txt)" >> $GITHUB_OUTPUT

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.flutter_version.outputs.version }}
        cache: true

    - name: Get package dependencies
      run: flutter pub get
      working-directory: ./

    - name: Get example dependencies
      run: flutter pub get
      working-directory: ./example

    - name: Start iPhone 16 Pro Simulator
      uses: futureware-tech/simulator-action@v3
      with:
        model: 'iPhone 16 Pro'
        os_version: '26.0'
      id: simulator

    - name: Run integration tests
      run: flutter test integration_test -d ${{ steps.simulator.outputs.udid }}
      working-directory: ./example

    - name: Upload golden test artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: integration_test-failures-ios
        path: |
          example/integration_test/failures
        retention-days: 30
